name: Build sources

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      working-directory: ./src/csharp
      run: dotnet restore
    
    - name: Build
      working-directory: ./src/csharp
      run: dotnet build --no-restore ZooKeeperNetEx.sln
